
server.port=8082
# Aiven Cloud MySQL Database Connection

spring.datasource.url=jdbc:mysql://lifesync-cloud-db-chiragmr676-e1dc.h.aivencloud.com:19529/defaultdb?sslMode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Explicitly tell Spring Boot to use MySQL (Fixes the Dialect error)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT Security Token Configuration
jwt.secret=${JWT_SECRET}
